# Generated by Django 5.1 on 2024-08-29 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='categoryName')),
                ('category_description', models.TextField(max_length=244, verbose_name='categoryDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30, verbose_name='postTitle')),
                ('post_content', models.TextField(verbose_name='postContent')),
                ('post_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='postCreateDate')),
                ('post_updated_date', models.DateTimeField(auto_now=True, verbose_name='postUpdateDate')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(null=True, verbose_name='commentContent')),
                ('comment_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='commentDateTime')),
                ('comment_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='commentUpdated')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
            ],
        ),
    ]
